local _, Addon = ...
local L = Addon.L
local C = Addon.Constants

Addon.Definition = {
    displayName = L.PLG_NAME_COMPASS,
    supportedClients = { retail = true, forever = true },
    alwaysEnabled = true,
    liveToggle = true,
    canvasMode = true,
    indexDefaults = {
        [C.NAVIGATION_SYSTEM_INDEX] = {
            Anchor = false,
            Position = false,
            NavigationSize = C.DEFAULT_NAVIGATION_SIZE,
            FontSize = C.DEFAULT_FONT_SIZE,
            DisabledComponents = {},
            ComponentPositions = {
                Name = {
                    version = 3,
                    mode = "free",
                    anchorBox = "OUTER",
                    policy = "TEXT",
                    anchorX = "RIGHT",
                    anchorY = "CENTER",
                    justifyH = "LEFT",
                    offsetXPx = -C.NAVIGATION_NAME_GAP,
                    offsetYPx = 0,
                },
                Distance = {
                    version = 3,
                    mode = "dock",
                    anchorBox = "OUTER",
                    policy = "TEXT",
                    anchorX = "CENTER",
                    anchorY = "BOTTOM",
                    justifyH = "CENTER",
                    selfAnchorY = "TOP",
                    edge = "BOTTOM",
                    targetKey = false,
                    targetReference = "CONTENT",
                    componentReference = "INWARD_EDGE",
                    normalOffsetPx = C.NAVIGATION_DISTANCE_GAP,
                    tangentAlign = "CENTER",
                    tangentOffsetPx = 0,
                },
            },
        },
    },
    defaults = {
        Enabled = true,
        ComponentSettings = {
            Name = { CustomColorCurve = { pins = { { position = 0, color = C.NAVIGATION_TEXT_COLOR } } } },
            Distance = { CustomColorCurve = { pins = { { position = 0, color = C.NAVIGATION_TEXT_COLOR } } } },
        },
        Width = C.DEFAULT_WIDTH,
        FontSize = C.DEFAULT_FONT_SIZE,
        IconSize = C.DEFAULT_ICON_SIZE,
        ViewAngle = C.DEFAULT_VIEW_ANGLE,
        Range = C.DEFAULT_RANGE,
        PointVisibility = {},
        ShowPOIs = true,
        ShowVignettes = true,
        ShowQuestObjectives = true,
        ShowWorldQuests = true,
        ShowFlightMasters = true,
        ShowEvents = true,
        ShowRaces = true,
        ShowQuestHubs = true,
        ShowWaypoint = true,
        ShowLabel = false,
        ShowDirections = true,
        ShowMapLinks = true,
        ShowPetTamers = true,
        ShowDigSites = true,
        ShowTrackedContent = true,
        ShowQuestOffers = true,
        ShowSavedLocations = true,
        ShowHandyNotes = true,
        ShowGatherMate = true,
        ShowCorpse = true,
        FollowTracked = true,
        AutoAdvanceMode = "off",
        AutoAdvanceSameType = true,
        Anchor = false,
        Position = { point = "TOP", x = 0, y = C.DEFAULT_Y },
    },
}
