local _, Addon = ...

local STRINGS = {
    enUS = {
        CMD_COMPASS_USAGE = "Usage: /way [#mapID] x y [name], /way <map link>, /way clear, or /way reset all. Coordinates: 0–100. /way works when unclaimed. Orbit aliases: /orbitway, /oway.",
        PLU_COMPASS_CITIES_TT = "Points shown in cities when Toggle is off.",
        PLU_COMPASS_OPEN_WORLD_TT = "Points shown outside cities when Toggle is off.",
        PLU_COMPASS_TOGGLE_TT = "Press the hotkey to show these points instead of Cities/World. Press it again to switch back.",
        PLU_COMPASS_OPEN_WORLD = "World",
        PLU_COMPASS_TOGGLE = "Toggle",
        PLU_COMPASS_POINT_HOTKEY = "Toggle hotkey",
        PLU_COMPASS_POINT_HOTKEY_TT = "Click to set a hotkey. Press Escape to cancel; right-click to clear. Uses your current WoW keybinding set.",
        PLU_COMPASS_POINT_TOGGLE_BINDING = "Toggle compass points",
        PLU_COMPASS_UNBOUND = "Not bound",
        PLU_COMPASS_PRESS_KEY = "Press a key",
        PLU_COMPASS_POINT_AREAS_TT = "Choose the normal points for Cities and World. Press the hotkey to show only the Toggle choices; press it again to return.",
        PLU_COMPASS_HANDYNOTES = "HandyNotes",
        PLU_COMPASS_HANDYNOTES_POINT_F = "%s — %.1f, %.1f",
        PLU_COMPASS_ARROW = "Arrow",
        PLU_COMPASS_ARROW_TITLE = "Compass: Arrow",
        PLU_COMPASS_POINT_TYPE = "Point type",
        PLU_COMPASS_CITIES = "Cities",
        PLU_COMPASS_POINT_AREA_F = "%s — %s",
        PLU_COMPASS_CHOOSE_POINT = "Choose a point to track",
        PLU_COMPASS_OVERLAP_HINT_F = "%d points here. Click to choose which to track.",
        MSG_COMPASS_NOT_READY = "Compass settings are unavailable.",
        MSG_COMPASS_INCOMPATIBLE_ORBIT = "Orbit: Compass could not start. Update Orbit, or disable Orbit and reload to use standalone Compass.",
        CMD_COMPASS_DISABLED = "Enable Compass in its settings to use the navigation arrow.",
    },
    deDE = {
        CMD_COMPASS_USAGE = "Verwendung: /way [#mapID] x y [Name], /way <Kartenlink>, /way clear oder /way reset all. Koordinaten: 0–100. /way funktioniert, wenn der Befehl nicht belegt ist. Orbit-Aliase: /orbitway, /oway.",
        PLU_COMPASS_CITIES_TT = "Punkte in Städten, wenn die alternative Auswahl deaktiviert ist.",
        PLU_COMPASS_OPEN_WORLD_TT = "Punkte außerhalb von Städten, wenn die alternative Auswahl deaktiviert ist.",
        PLU_COMPASS_TOGGLE_TT = "Die Tastenkombination zeigt diese Punkte statt der Auswahl für Städte/Welt. Erneutes Drücken schaltet zurück.",
        PLU_COMPASS_OPEN_WORLD = "Welt",
        PLU_COMPASS_TOGGLE = "Umschalten",
        PLU_COMPASS_POINT_HOTKEY = "Umschalttaste",
        PLU_COMPASS_POINT_HOTKEY_TT = "Klicken, um eine Tastenkombination festzulegen. Escape bricht ab; Rechtsklick entfernt sie. Verwendet Eure aktuellen WoW-Tastenbelegungen.",
        PLU_COMPASS_POINT_TOGGLE_BINDING = "Kompasspunkte umschalten",
        PLU_COMPASS_UNBOUND = "Nicht belegt",
        PLU_COMPASS_PRESS_KEY = "Taste drücken",
        PLU_COMPASS_POINT_AREAS_TT = "Wählt die normalen Punkte für Städte und Welt. Die Tastenkombination zeigt nur die Auswahl unter Umschalten; erneutes Drücken kehrt zurück.",
        PLU_COMPASS_HANDYNOTES = "HandyNotes",
        PLU_COMPASS_HANDYNOTES_POINT_F = "%s — %.1f, %.1f",
        PLU_COMPASS_ARROW = "Pfeil",
        PLU_COMPASS_ARROW_TITLE = "Kompass: Pfeil",
        PLU_COMPASS_POINT_TYPE = "Punkttyp",
        PLU_COMPASS_CITIES = "Städte",
        PLU_COMPASS_POINT_AREA_F = "%s — %s",
        PLU_COMPASS_CHOOSE_POINT = "Wählt einen Punkt zur Verfolgung",
        PLU_COMPASS_OVERLAP_HINT_F = "%d Punkte an dieser Stelle. Klickt, um einen zur Verfolgung auszuwählen.",
        MSG_COMPASS_NOT_READY = "Kompass-Einstellungen sind nicht verfügbar.",
        MSG_COMPASS_INCOMPATIBLE_ORBIT = "Orbit: Kompass konnte nicht gestartet werden. Aktualisiert Orbit oder deaktiviert Orbit und ladet die Benutzeroberfläche neu, um den Kompass eigenständig zu nutzen.",
        CMD_COMPASS_DISABLED = "Aktiviert den Kompass in seinen Einstellungen, um den Navigationspfeil zu verwenden.",
    },
    frFR = {
        CMD_COMPASS_USAGE = "Utilisation : /way [#mapID] x y [nom], /way <lien de carte>, /way clear ou /way reset all. Coordonnées : 0–100. /way fonctionne si cette commande est libre. Alias Orbit : /orbitway, /oway.",
        PLU_COMPASS_CITIES_TT = "Points affichés en ville lorsque la sélection alternative est désactivée.",
        PLU_COMPASS_OPEN_WORLD_TT = "Points affichés hors des villes lorsque la sélection alternative est désactivée.",
        PLU_COMPASS_TOGGLE_TT = "Le raccourci affiche ces points à la place de Villes/Monde. Appuyez à nouveau pour revenir.",
        PLU_COMPASS_OPEN_WORLD = "Monde",
        PLU_COMPASS_TOGGLE = "Basculer",
        PLU_COMPASS_POINT_HOTKEY = "Raccourci de bascule",
        PLU_COMPASS_POINT_HOTKEY_TT = "Cliquez pour définir un raccourci. Échap annule ; un clic droit le supprime. Utilise vos raccourcis WoW actuels.",
        PLU_COMPASS_POINT_TOGGLE_BINDING = "Basculer les points de la boussole",
        PLU_COMPASS_UNBOUND = "Non attribué",
        PLU_COMPASS_PRESS_KEY = "Appuyez sur une touche",
        PLU_COMPASS_POINT_AREAS_TT = "Choisissez les points habituels pour Villes et Monde. Le raccourci affiche uniquement la sélection Basculer ; appuyez à nouveau pour revenir.",
        PLU_COMPASS_HANDYNOTES = "HandyNotes",
        PLU_COMPASS_HANDYNOTES_POINT_F = "%s — %.1f, %.1f",
        PLU_COMPASS_ARROW = "Flèche",
        PLU_COMPASS_ARROW_TITLE = "Boussole : Flèche",
        PLU_COMPASS_POINT_TYPE = "Type de point",
        PLU_COMPASS_CITIES = "Villes",
        PLU_COMPASS_POINT_AREA_F = "%s — %s",
        PLU_COMPASS_CHOOSE_POINT = "Choisissez un point à suivre",
        PLU_COMPASS_OVERLAP_HINT_F = "%d points ici. Cliquez pour choisir lequel suivre.",
        MSG_COMPASS_NOT_READY = "Les paramètres de la boussole sont indisponibles.",
        MSG_COMPASS_INCOMPATIBLE_ORBIT = "Orbit : la boussole n’a pas pu démarrer. Mettez Orbit à jour, ou désactivez Orbit et rechargez l’interface pour utiliser la boussole seule.",
        CMD_COMPASS_DISABLED = "Activez la boussole dans ses paramètres pour utiliser la flèche de navigation.",
    },
    esES = {
        CMD_COMPASS_USAGE = "Uso: /way [#mapID] x y [nombre], /way <enlace de mapa>, /way clear o /way reset all. Coordenadas: 0–100. /way funciona si está libre. Alias de Orbit: /orbitway, /oway.",
        PLU_COMPASS_CITIES_TT = "Puntos mostrados en ciudades cuando la selección alternativa está desactivada.",
        PLU_COMPASS_OPEN_WORLD_TT = "Puntos mostrados fuera de las ciudades cuando la selección alternativa está desactivada.",
        PLU_COMPASS_TOGGLE_TT = "Pulsa el atajo para mostrar estos puntos en lugar de Ciudades/Mundo. Púlsalo de nuevo para volver.",
        PLU_COMPASS_OPEN_WORLD = "Mundo",
        PLU_COMPASS_TOGGLE = "Alternar",
        PLU_COMPASS_POINT_HOTKEY = "Atajo para alternar",
        PLU_COMPASS_POINT_HOTKEY_TT = "Haz clic para asignar un atajo. Escape cancela; clic derecho lo elimina. Usa tu configuración actual de teclas de WoW.",
        PLU_COMPASS_POINT_TOGGLE_BINDING = "Alternar puntos de la brújula",
        PLU_COMPASS_UNBOUND = "Sin asignar",
        PLU_COMPASS_PRESS_KEY = "Pulsa una tecla",
        PLU_COMPASS_POINT_AREAS_TT = "Elige los puntos normales para Ciudades y Mundo. El atajo muestra solo la selección de Alternar; púlsalo de nuevo para volver.",
        PLU_COMPASS_HANDYNOTES = "HandyNotes",
        PLU_COMPASS_HANDYNOTES_POINT_F = "%s — %.1f, %.1f",
        PLU_COMPASS_ARROW = "Flecha",
        PLU_COMPASS_ARROW_TITLE = "Brújula: Flecha",
        PLU_COMPASS_POINT_TYPE = "Tipo de punto",
        PLU_COMPASS_CITIES = "Ciudades",
        PLU_COMPASS_POINT_AREA_F = "%s — %s",
        PLU_COMPASS_CHOOSE_POINT = "Elige un punto para seguir",
        PLU_COMPASS_OVERLAP_HINT_F = "%d puntos aquí. Haz clic para elegir cuál seguir.",
        MSG_COMPASS_NOT_READY = "Los ajustes de la brújula no están disponibles.",
        MSG_COMPASS_INCOMPATIBLE_ORBIT = "Orbit: No se pudo iniciar la brújula. Actualiza Orbit o desactívalo y recarga la interfaz para usar la brújula de forma independiente.",
        CMD_COMPASS_DISABLED = "Activa la brújula en sus ajustes para usar la flecha de navegación.",
    },
    ptBR = {
        CMD_COMPASS_USAGE = "Uso: /way [#mapID] x y [nome], /way <link do mapa>, /way clear ou /way reset all. Coordenadas: 0–100. /way funciona quando está livre. Atalhos do Orbit: /orbitway, /oway.",
        PLU_COMPASS_CITIES_TT = "Pontos exibidos nas cidades quando a seleção alternativa está desativada.",
        PLU_COMPASS_OPEN_WORLD_TT = "Pontos exibidos fora das cidades quando a seleção alternativa está desativada.",
        PLU_COMPASS_TOGGLE_TT = "Pressione o atalho para mostrar estes pontos no lugar de Cidades/Mundo. Pressione novamente para voltar.",
        PLU_COMPASS_OPEN_WORLD = "Mundo",
        PLU_COMPASS_TOGGLE = "Alternar",
        PLU_COMPASS_POINT_HOTKEY = "Atalho para alternar",
        PLU_COMPASS_POINT_HOTKEY_TT = "Clique para definir um atalho. Escape cancela; clique direito remove. Usa suas teclas de atalho atuais do WoW.",
        PLU_COMPASS_POINT_TOGGLE_BINDING = "Alternar pontos da bússola",
        PLU_COMPASS_UNBOUND = "Não atribuído",
        PLU_COMPASS_PRESS_KEY = "Pressione uma tecla",
        PLU_COMPASS_POINT_AREAS_TT = "Escolha os pontos normais para Cidades e Mundo. O atalho mostra apenas a seleção de Alternar; pressione novamente para voltar.",
        PLU_COMPASS_HANDYNOTES = "HandyNotes",
        PLU_COMPASS_HANDYNOTES_POINT_F = "%s — %.1f, %.1f",
        PLU_COMPASS_ARROW = "Seta",
        PLU_COMPASS_ARROW_TITLE = "Bússola: Seta",
        PLU_COMPASS_POINT_TYPE = "Tipo de ponto",
        PLU_COMPASS_CITIES = "Cidades",
        PLU_COMPASS_POINT_AREA_F = "%s — %s",
        PLU_COMPASS_CHOOSE_POINT = "Escolha um ponto para rastrear",
        PLU_COMPASS_OVERLAP_HINT_F = "%d pontos aqui. Clique para escolher qual rastrear.",
        MSG_COMPASS_NOT_READY = "As configurações da bússola estão indisponíveis.",
        MSG_COMPASS_INCOMPATIBLE_ORBIT = "Orbit: Não foi possível iniciar a bússola. Atualize o Orbit ou desative-o e recarregue a interface para usar a bússola de forma independente.",
        CMD_COMPASS_DISABLED = "Ative a bússola nas configurações para usar a seta de navegação.",
    },
    ruRU = {
        CMD_COMPASS_USAGE = "Использование: /way [#mapID] x y [название], /way <ссылка на карту>, /way clear или /way reset all. Координаты: 0–100. /way работает, если команда не занята. Псевдонимы Orbit: /orbitway, /oway.",
        PLU_COMPASS_CITIES_TT = "Точки в городах, когда альтернативный набор выключен.",
        PLU_COMPASS_OPEN_WORLD_TT = "Точки вне городов, когда альтернативный набор выключен.",
        PLU_COMPASS_TOGGLE_TT = "Горячая клавиша показывает эти точки вместо набора для городов/мира. Нажмите ещё раз, чтобы вернуться.",
        PLU_COMPASS_OPEN_WORLD = "Мир",
        PLU_COMPASS_TOGGLE = "Переключение",
        PLU_COMPASS_POINT_HOTKEY = "Клавиша переключения",
        PLU_COMPASS_POINT_HOTKEY_TT = "Нажмите, чтобы назначить клавишу. Escape — отмена, правая кнопка мыши — сброс. Используется текущий набор клавиш WoW.",
        PLU_COMPASS_POINT_TOGGLE_BINDING = "Переключить точки компаса",
        PLU_COMPASS_UNBOUND = "Не назначено",
        PLU_COMPASS_PRESS_KEY = "Нажмите клавишу",
        PLU_COMPASS_POINT_AREAS_TT = "Выберите обычные точки для городов и мира. Горячая клавиша показывает только точки из столбца «Переключение»; повторное нажатие возвращает обычный вид.",
        PLU_COMPASS_HANDYNOTES = "HandyNotes",
        PLU_COMPASS_HANDYNOTES_POINT_F = "%s — %.1f, %.1f",
        PLU_COMPASS_ARROW = "Стрелка",
        PLU_COMPASS_ARROW_TITLE = "Компас: Стрелка",
        PLU_COMPASS_POINT_TYPE = "Тип точки",
        PLU_COMPASS_CITIES = "Города",
        PLU_COMPASS_POINT_AREA_F = "%s — %s",
        PLU_COMPASS_CHOOSE_POINT = "Выберите точку для отслеживания",
        PLU_COMPASS_OVERLAP_HINT_F = "Здесь %d точек. Нажмите, чтобы выбрать точку для отслеживания.",
        MSG_COMPASS_NOT_READY = "Настройки компаса недоступны.",
        MSG_COMPASS_INCOMPATIBLE_ORBIT = "Orbit: Не удалось запустить компас. Обновите Orbit или отключите его и перезагрузите интерфейс, чтобы использовать компас отдельно.",
        CMD_COMPASS_DISABLED = "Включите компас в его настройках, чтобы использовать навигационную стрелку.",
    },
    koKR = {
        CMD_COMPASS_USAGE = "사용법: /way [#mapID] x y [이름], /way <지도 링크>, /way clear 또는 /way reset all. 좌표: 0–100. /way는 다른 애드온이 사용하지 않을 때 작동합니다. Orbit 별칭: /orbitway, /oway.",
        PLU_COMPASS_CITIES_TT = "전환 모드가 꺼져 있을 때 도시에서 표시되는 지점입니다.",
        PLU_COMPASS_OPEN_WORLD_TT = "전환 모드가 꺼져 있을 때 도시 밖에서 표시되는 지점입니다.",
        PLU_COMPASS_TOGGLE_TT = "단축키를 누르면 도시/세계 선택 대신 이 지점들을 표시합니다. 다시 누르면 원래 표시로 돌아갑니다.",
        PLU_COMPASS_OPEN_WORLD = "세계",
        PLU_COMPASS_TOGGLE = "전환",
        PLU_COMPASS_POINT_HOTKEY = "전환 단축키",
        PLU_COMPASS_POINT_HOTKEY_TT = "클릭하여 단축키를 지정합니다. Escape로 취소하고 오른쪽 클릭으로 해제합니다. 현재 WoW 단축키 설정을 사용합니다.",
        PLU_COMPASS_POINT_TOGGLE_BINDING = "나침반 지점 전환",
        PLU_COMPASS_UNBOUND = "미지정",
        PLU_COMPASS_PRESS_KEY = "키를 누르세요",
        PLU_COMPASS_POINT_AREAS_TT = "도시와 세계에서 표시할 기본 지점을 선택하세요. 단축키를 누르면 전환 열에서 선택한 지점만 표시하고, 다시 누르면 기본 표시로 돌아갑니다.",
        PLU_COMPASS_HANDYNOTES = "HandyNotes",
        PLU_COMPASS_HANDYNOTES_POINT_F = "%s — %.1f, %.1f",
        PLU_COMPASS_ARROW = "화살표",
        PLU_COMPASS_ARROW_TITLE = "나침반: 화살표",
        PLU_COMPASS_POINT_TYPE = "지점 유형",
        PLU_COMPASS_CITIES = "도시",
        PLU_COMPASS_POINT_AREA_F = "%s — %s",
        PLU_COMPASS_CHOOSE_POINT = "추적할 지점을 선택하세요",
        PLU_COMPASS_OVERLAP_HINT_F = "여기에 지점이 %d개 있습니다. 클릭하여 추적할 지점을 선택하세요.",
        MSG_COMPASS_NOT_READY = "나침반 설정을 사용할 수 없습니다.",
        MSG_COMPASS_INCOMPATIBLE_ORBIT = "Orbit: 나침반을 시작할 수 없습니다. Orbit을 업데이트하거나 비활성화한 후 UI를 재시작하면 나침반을 독립적으로 사용할 수 있습니다.",
        CMD_COMPASS_DISABLED = "이동 방향 화살표를 사용하려면 설정에서 나침반을 활성화하세요.",
    },
    zhCN = {
        CMD_COMPASS_USAGE = "用法：/way [#mapID] x y [名称]、/way <地图链接>、/way clear 或 /way reset all。坐标范围：0–100。/way 在未被占用时可用。Orbit 别名：/orbitway、/oway。",
        PLU_COMPASS_CITIES_TT = "未启用切换模式时，在城市中显示的标记。",
        PLU_COMPASS_OPEN_WORLD_TT = "未启用切换模式时，在城市外显示的标记。",
        PLU_COMPASS_TOGGLE_TT = "按快捷键显示这些标记，取代城市/世界中的选择。再按一次切换回来。",
        PLU_COMPASS_OPEN_WORLD = "世界",
        PLU_COMPASS_TOGGLE = "切换",
        PLU_COMPASS_POINT_HOTKEY = "切换快捷键",
        PLU_COMPASS_POINT_HOTKEY_TT = "点击设置快捷键。按Escape取消，右键点击清除。使用当前的WoW按键设置。",
        PLU_COMPASS_POINT_TOGGLE_BINDING = "切换罗盘标记",
        PLU_COMPASS_UNBOUND = "未绑定",
        PLU_COMPASS_PRESS_KEY = "请按一个键",
        PLU_COMPASS_POINT_AREAS_TT = "选择城市和世界中通常显示的标记。按快捷键仅显示“切换”列中的选项，再按一次恢复通常显示。",
        PLU_COMPASS_HANDYNOTES = "HandyNotes",
        PLU_COMPASS_HANDYNOTES_POINT_F = "%s — %.1f, %.1f",
        PLU_COMPASS_ARROW = "箭头",
        PLU_COMPASS_ARROW_TITLE = "指南针：箭头",
        PLU_COMPASS_POINT_TYPE = "标记类型",
        PLU_COMPASS_CITIES = "城市",
        PLU_COMPASS_POINT_AREA_F = "%s — %s",
        PLU_COMPASS_CHOOSE_POINT = "选择要追踪的标记",
        PLU_COMPASS_OVERLAP_HINT_F = "此处有%d个标记。点击选择要追踪的标记。",
        MSG_COMPASS_NOT_READY = "罗盘设置不可用。",
        MSG_COMPASS_INCOMPATIBLE_ORBIT = "Orbit：无法启动指南针。请更新 Orbit，或禁用 Orbit 并重载界面，以独立使用指南针。",
        CMD_COMPASS_DISABLED = "请在设置中启用罗盘以使用导航箭头。",
    },
    zhTW = {
        CMD_COMPASS_USAGE = "用法：/way [#mapID] x y [名稱]、/way <地圖連結>、/way clear 或 /way reset all。座標範圍：0–100。/way 在未被佔用時可用。Orbit 別名：/orbitway、/oway。",
        PLU_COMPASS_CITIES_TT = "未啟用切換模式時，在城市中顯示的標記。",
        PLU_COMPASS_OPEN_WORLD_TT = "未啟用切換模式時，在城市外顯示的標記。",
        PLU_COMPASS_TOGGLE_TT = "按快捷鍵顯示這些標記，取代城市/世界中的選擇。再按一次切換回來。",
        PLU_COMPASS_OPEN_WORLD = "世界",
        PLU_COMPASS_TOGGLE = "切換",
        PLU_COMPASS_POINT_HOTKEY = "切換快捷鍵",
        PLU_COMPASS_POINT_HOTKEY_TT = "點擊設定快捷鍵。按Escape取消，右鍵點擊清除。使用目前的WoW按鍵設定。",
        PLU_COMPASS_POINT_TOGGLE_BINDING = "切換指南針標記",
        PLU_COMPASS_UNBOUND = "未綁定",
        PLU_COMPASS_PRESS_KEY = "請按一個鍵",
        PLU_COMPASS_POINT_AREAS_TT = "選擇城市與世界中通常顯示的標記。按快捷鍵僅顯示「切換」欄中的選項，再按一次恢復通常顯示。",
        PLU_COMPASS_HANDYNOTES = "HandyNotes",
        PLU_COMPASS_HANDYNOTES_POINT_F = "%s — %.1f, %.1f",
        PLU_COMPASS_ARROW = "箭頭",
        PLU_COMPASS_ARROW_TITLE = "指南針：箭頭",
        PLU_COMPASS_POINT_TYPE = "標記類型",
        PLU_COMPASS_CITIES = "城市",
        PLU_COMPASS_POINT_AREA_F = "%s — %s",
        PLU_COMPASS_CHOOSE_POINT = "選擇要追蹤的標記",
        PLU_COMPASS_OVERLAP_HINT_F = "此處有%d個標記。點擊選擇要追蹤的標記。",
        MSG_COMPASS_NOT_READY = "羅盤設定無法使用。",
        MSG_COMPASS_INCOMPATIBLE_ORBIT = "Orbit：無法啟動指南針。請更新 Orbit，或停用 Orbit 並重新載入介面，以獨立使用指南針。",
        CMD_COMPASS_DISABLED = "請在設定中啟用羅盤以使用導航箭頭。",
    },
}

local host = Addon.OrbitHost
if host then
    for key in pairs(Addon.L) do
        local value = rawget(host.L, key)
        if value ~= nil then
            Addon.L[key] = value
        end
    end
end

local locale = host and host.Localization and host.Localization.activeLocale or GetLocale()
if locale == "enGB" then
    locale = "enUS"
end
if locale == "esMX" then
    locale = "esES"
end
for key, value in pairs(STRINGS[locale] or STRINGS.enUS) do
    Addon.L[key] = value
end
if not Addon.incompatibleOrbit then
    _G.BINDING_HEADER_ORBIT_COMPASS = Addon.L.PLG_NAME_COMPASS
end
